responses:
  401:
    body:
      type: object
      example: !include json/errorStatus.json
  403:
    body:
      type: object
      example: !include json/errorStatus.json
  404:
    body:
      type: object
      example: !include json/errorStatus.json